//
//  WrapPickerDataSource.swift
//  meWrap
//
//  Created by Sergey Maximenko on 11/12/15.
//  Copyright © 2015 Ravenpod. All rights reserved.
//

import UIKit

class WrapPickerDataSource: StreamDataSource {
    
    var didEndScrollingAnimationBlock: (Void -> Void)?
    
    func scrollViewWillEndDragging(scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        targetContentOffset.memory.y = round(targetContentOffset.memory.y / autogeneratedMetrics.size) * autogeneratedMetrics.size
    }
    
    func scrollViewDidEndScrollingAnimation(scrollView: UIScrollView) {
        if let block = didEndScrollingAnimationBlock {
            block()
            didEndScrollingAnimationBlock = nil
        }
    }
}
