//
//  TestUserPicker.swift
//  meWrap
//
//  Created by Sergey Maximenko on 2/4/16.
//  Copyright © 2016 Ravenpod. All rights reserved.
//

import UIKit
import SnapKit

class TestUserCell: StreamReusableView, FlowerMenuConstructor {
    
    @IBOutlet weak var phone: UILabel!
    @IBOutlet weak var email: UILabel!
    @IBOutlet weak var deviceUID: UILabel!
    @IBOutlet weak var active: UIView!
    
    override func awakeFromNib() {
        super.awakeFromNib()
        FlowerMenu.sharedMenu.registerView(self)
    }
    
    func constructFlowerMenu(menu: FlowerMenu) {
        menu.addDeleteAction { [weak self] () -> Void in
            if let authorization = self?.entry as? Authorization {
                Environment.removeTestUser(authorization, completion: {
                    Environment.current.testUsers { [weak self] authorizations in
                        (self?.superview?.superview as? TestUserPicker)?.dataSource.items = authorizations
                    }
                })
            }
        }
    }
    
    override func setup(entry: AnyObject?) {
        if let authorization = entry as? Authorization {
            phone.text = authorization.fullPhoneNumber
            email.text = authorization.email
            deviceUID.text = authorization.deviceUID
            active.hidden = authorization.password?.isEmpty ?? true
        }
    }
}

final class TestUserPicker: UIView {
    
    private let titleLabel = UILabel()
    private let closeButton = UIButton(type: .Custom)
    private let navigationBar = UIView()
    private let streamView = StreamView()
    private var dataSource: StreamDataSource!
    
    class func showInView(view: UIView, selection: Authorization -> Void) {
        TestUserPicker(frame: view.bounds).showInView(view, selection: selection)
    }
    
    private func showInView(view: UIView, selection: Authorization -> Void) {
        titleLabel.text = "Select user"
        titleLabel.textColor = UIColor.whiteColor()
        closeButton.setTitle("Close", forState: .Normal)
        navigationBar.backgroundColor = Color.orange
        backgroundColor = UIColor.whiteColor()
        dataSource = StreamDataSource(streamView: streamView)
        dataSource.autogeneratedMetrics.change {
            $0.identifier = "TestUserCell"
            $0.size = 110
            $0.selection = { [weak self] item, entry in
                self?.removeFromSuperview()
                selection(entry as! Authorization)
            }
        }
        navigationBar.addSubview(closeButton)
        navigationBar.addSubview(titleLabel)
        addSubview(navigationBar)
        addSubview(streamView)
        view.addSubview(self)
        
        navigationBar.snp_makeConstraints { (make) -> Void in
            make.top.left.right.equalTo(self)
            make.height.equalTo(64)
        }
        
        closeButton.snp_makeConstraints { (make) -> Void in
            make.centerY.equalTo(navigationBar).offset(10)
            make.left.equalTo(navigationBar).offset(12)
        }
        
        titleLabel.snp_makeConstraints { (make) -> Void in
            make.centerY.equalTo(navigationBar).offset(10)
            make.centerX.equalTo(navigationBar)
        }
        
        streamView.snp_makeConstraints { (make) -> Void in
            make.top.equalTo(navigationBar.snp_bottom)
            make.bottom.left.right.equalTo(self)
        }
        
        layoutIfNeeded()
        closeButton.addTarget(self, action: "removeFromSuperview", forControlEvents: .TouchUpInside)
        
        Environment.current.testUsers { [weak self] authorizations in
            self?.dataSource.items = authorizations
        }
    }
}
